---
- name: make sure zfs is installed
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - zfs-dkms
    - zfsutils-linux
- copy:
   src: files/zfs-module.conf
   dest: /etc/modules-load.d/zfs-module.conf
   mode: "0644"
   owner: root
   group: root
  register: zfs_module_conf_file
- name: make sure zfs module is present
  shell: modprobe zfs
  when: zfs_module_conf_file.changed
- import_tasks: zpool_create.yml
  with_dict: "{{ zpool_create }}"
  loop_control:
    loop_var: zpool_item
